'use client';

import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { motion, AnimatePresence } from 'framer-motion';
import {
  ShieldCheck, User, ShieldAlert, Landmark, Car, Coins,
  ArrowRight, Eye, EyeOff, Lock, Globe, CheckCircle2,
  Package, UserCheck, Hash, AlertTriangle, Building2
} from 'lucide-react';
import { STORAGE_CONFIGURED } from '@/lib/ipfs';

// ─── Wallet Auto-Generation ───────────────────────────────────────────────────
async function generateWalletFromSeed(seed: string): Promise<string> {
  const buf  = new TextEncoder().encode(seed);
  const hash = await crypto.subtle.digest('SHA-256', buf);
  const hex  = Array.from(new Uint8Array(hash)).map(b => b.toString(16).padStart(2, '0')).join('');
  return '0x' + hex.slice(0, 40); // Ethereum-style: 20 bytes = 40 hex chars
}

// ─── Types ────────────────────────────────────────────────────────────────────
export interface VerificatorAccount {
  username:    string;   // untuk login
  name:        string;   // nama lengkap
  wallet:      string;   // alamat wallet 0x... (auto-generated by hash)
  institution: string;   // BPN | Samsat | Pegadaian | Kemenkeu
  passwordHash: string;  // SHA-256(password) — tidak pernah simpan plain text
  status:      'pending' | 'approved' | 'rejected';
  registeredAt: string;
}

// ─── Simple SHA-256 untuk password hashing (browser native) ──────────────────
async function hashPassword(password: string): Promise<string> {
  const buf  = new TextEncoder().encode(password);
  const hash = await crypto.subtle.digest('SHA-256', buf);
  return Array.from(new Uint8Array(hash)).map(b => b.toString(16).padStart(2, '0')).join('');
}

// ─── localStorage helpers ─────────────────────────────────────────────────────
function getVerificatorAccounts(): VerificatorAccount[] {
  return JSON.parse(localStorage.getItem('bb_verificator_accounts') || '[]');
}
function saveVerificatorAccounts(accounts: VerificatorAccount[]) {
  localStorage.setItem('bb_verificator_accounts', JSON.stringify(accounts));
}

// ─── Component ────────────────────────────────────────────────────────────────
export default function LandingPage() {
  const router = useRouter();
  const [tab, setTab] = useState<'login' | 'register-user'>('login');
  const [showPw, setShowPw] = useState(false);
  const [error, setError] = useState('');

  // User login
  const [loginEmail, setLoginEmail] = useState('');
  const [loginPw, setLoginPw]       = useState('');

  // User register
  const [regName,  setRegName]  = useState('');
  const [regEmail, setRegEmail] = useState('');
  const [regPw,    setRegPw]    = useState('');
  const [regWallet, setRegWallet] = useState(''); // auto-generated wallet

  // Auto-redirect jika sudah login
  useEffect(() => {
    const s = localStorage.getItem('bb_session');
    if (s) {
      const { role } = JSON.parse(s);
      if (role === 'user')        router.push('/user');
      if (role === 'admin')       router.push('/admin');
      if (role === 'verificator') router.push('/verificator');
    }
  }, [router]);
  const clear = () => { setError(''); };

  // ── Login User ───────────────────────────────────────────────────────────
  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault(); clear();
    
    // 1. Fetch Central DB users
    const res = await fetch('/api/db?table=users');
    const allUsers: any[] = res.ok ? await res.json() : [];
    
    // 2. Local fallback
    const localUsers: Record<string, any> = JSON.parse(localStorage.getItem('bb_users') || '{}');
    
    // Decision Logic: prioritaskan central
    let u = allUsers.find(user => user.email === loginEmail);
    
    if (!u) {
      // Jika di Central tidak ada, tapi di Local ada...
      if (localUsers[loginEmail]) {
        // Jika Central DB sudah berisi user lain, berarti user ini kemungkinan besar sudah dihapus oleh Admin
        if (allUsers.length > 0) {
          return setError('Akun Anda telah dinonaktifkan atau dihapus oleh SuperAdmin.');
        }
        // Fallback: Jika Central DB benar-benar kosong, anggap ini user lama yang sedang sync
        u = localUsers[loginEmail];
        // Auto-sync ke Central DB biar kedepannya terhapus global
        await fetch('/api/db', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ table: 'users', action: 'insert', payload: u })
        });
      }
    }

    if (!u) return setError('Email tidak ditemukan. Silakan daftar terlebih dahulu.');
    if (u.password !== loginPw) return setError('Password salah.');
    
    localStorage.setItem('bb_session', JSON.stringify({ role: 'user', name: u.name, email: loginEmail, wallet: u.wallet }));
    router.push('/user');
  };

  // ── Register User — dengan auto-generate wallet ───────────────────────────
  const handleRegisterUser = async (e: React.FormEvent) => {
    e.preventDefault(); clear();
    if (!regName.trim() || !regEmail.trim() || !regPw.trim()) return setError('Semua field wajib diisi.');
    if (regPw.length < 6) return setError('Password minimal 6 karakter.');
    
    // 1. Check Central DB for existing email
    const resExist = await fetch('/api/db?table=users');
    const allUsers: any[] = resExist.ok ? await resExist.json() : [];
    const existsCentrally = allUsers.find(u => u.email === regEmail);
    
    if (existsCentrally) return setError('Email sudah terdaftar di server. Silakan login.');

    // 2. Local fallback check & Cache cleaning
    const localUsers: Record<string, any> = JSON.parse(localStorage.getItem('bb_users') || '{}');
    
    if (localUsers[regEmail]) {
      // Jika di Central DB tidak ada, tapi di Local ada, anggap cache usang (terhapus oleh Admin)
      console.log("Stale local cache detected for deleted user. Overwriting for re-registration.");
    }

    // Auto-generate wallet address dari hash email + name + timestamp
    const seed   = `BB::User::${regEmail}::${regName}::${Date.now()}`;
    const wallet = await generateWalletFromSeed(seed);

    const newUser = { email: regEmail, password: regPw, name: regName, wallet };

    // 3. Save to Central DB (api/db)
    await fetch('/api/db', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ table: 'users', action: 'insert', payload: newUser })
    });

    // 4. Save to LocalStorage (legacy fallback)
    localUsers[regEmail] = newUser;
    localStorage.setItem('bb_users', JSON.stringify(localUsers));

    localStorage.setItem('bb_session', JSON.stringify({ role: 'user', name: regName, email: regEmail, wallet }));
    router.push('/user');
  };

  const features = [
    { icon: <Lock size={16} className="text-emerald-500" />,       text: 'Dokumen di-hash on-chain via IPFS' },
    { icon: <ShieldCheck size={16} className="text-emerald-500" />, text: 'Verifikasi trustless oleh Notaris/Oracle' },
    { icon: <Globe size={16} className="text-emerald-500" />,       text: 'Properti · Kendaraan · Emas ↔ Digital' },
    { icon: <CheckCircle2 size={16} className="text-emerald-500" />,text: 'Deploy di Base Sepolia Testnet' },
  ];

  // Real protocol metadata
  const protocolInfo = [
    { v: '0.001 ETH', l: 'Validation Fee' },
    { v: 'Base Sepolia', l: 'Network' },
    { v: '80 / 20', l: 'Fee Split (V/Admin)' },
    { v: 'SHA-256', l: 'Hash Algorithm' },
  ];

  return (
    <div className="min-h-screen bg-white overflow-x-hidden">

      {/* ── Abstract Background ── */}
      <div className="fixed inset-0 -z-10 overflow-hidden pointer-events-none">
        <motion.div animate={{ scale:[1,1.2,1], rotate:[0,120,0], borderRadius:['40% 60%','60% 40%','40% 60%'] }}
          transition={{ duration:22, repeat:Infinity, ease:'easeInOut' }}
          className="absolute -top-40 -left-52 w-[650px] h-[650px] bg-emerald-100/60 blur-[80px]" />
        <motion.div animate={{ scale:[1,1.15,1], rotate:[0,-80,0] }}
          transition={{ duration:18, repeat:Infinity, ease:'easeInOut' }}
          className="absolute top-1/2 right-[-20%] w-[550px] h-[550px] bg-teal-100/40 blur-[100px]" />
        <motion.div animate={{ scale:[1,1.1,1] }} transition={{ duration:14, repeat:Infinity }}
          className="absolute bottom-[-10%] left-1/3 w-[400px] h-[400px] bg-blue-50/50 blur-[80px]" />
      </div>

      {/* ── Minimal Navbar ── */}
      <nav className="sticky top-0 z-50 bg-white/80 backdrop-blur-xl border-b border-slate-100">
        <div className="max-w-7xl mx-auto px-4 md:px-8 h-14 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-7 h-7 bg-emerald-600 rounded-lg flex items-center justify-center">
              <span className="text-white font-black text-[10px]">BB</span>
            </div>
            <span className="font-black text-slate-900">BangBang</span>
          </div>
          <div className="flex items-center gap-2 text-xs">
          </div>
        </div>
      </nav>

      <div className="max-w-7xl mx-auto px-4 md:px-8">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 py-14 lg:py-20 items-start">

          {/* ── LEFT: Hero ── */}
          <motion.div initial={{ opacity:0, y:16 }} animate={{ opacity:1, y:0 }} className="space-y-7">
            <div className="space-y-3">
              <h1 className="text-5xl md:text-6xl font-black text-slate-900 tracking-tighter leading-[1.05]">
                Bikin Aset Fisikmu<br />
                <span className="text-emerald-600">Jadi Digital & <br/>Terpercaya.</span>
              </h1>
              <p className="text-slate-500 text-base leading-relaxed max-w-md">
                Gak perlu ribet urus berkas fisik terus-menerus. Di BangBang, kamu bisa simpan bukti kepemilikan asetmu—dari tanah sampai emas—langsung di blockchain. Semuanya aman, transparan, dan pastinya gak bisa dipalsu.
              </p>
            </div>



            {/* Protocol Info — real values */}
            <div className="grid grid-cols-4 gap-3">
              {protocolInfo.map((s, i) => (
                <div key={i} className="text-center p-3 bg-white border border-slate-100 rounded-2xl shadow-sm">
                  <p className="text-sm font-black text-slate-900 leading-tight">{s.v}</p>
                  <p className="text-[9px] text-slate-400 font-bold uppercase tracking-wider mt-0.5">{s.l}</p>
                </div>
              ))}
            </div>



            {/* Category icons */}
            <div className="flex items-center gap-4">
              <p className="text-xs text-slate-400 font-bold">Supported:</p>
              <div className="flex items-center gap-3">
                {[
                  { icon: <Landmark size={16} />, label: 'Property', c: 'text-emerald-600 bg-emerald-50' },
                  { icon: <Car size={16} />, label: 'Vehicle', c: 'text-blue-600 bg-blue-50' },
                  { icon: <Coins size={16} />, label: 'Gold', c: 'text-amber-500 bg-amber-50' },
                  { icon: <Package size={16} />, label: 'Other', c: 'text-purple-500 bg-purple-50' },
                ].map(a => (
                  <div key={a.label} className={`flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg text-[10px] font-bold ${a.c}`}>
                    {a.icon} {a.label}
                  </div>
                ))}
              </div>
            </div>
          </motion.div>

          {/* ── RIGHT: Auth Card ── */}
          <motion.div initial={{ opacity:0, x:20 }} animate={{ opacity:1, x:0 }} transition={{ delay:0.05 }}
            className="lg:sticky lg:top-20">
            <div className="bg-white border border-slate-200 rounded-3xl shadow-xl shadow-slate-100/80 overflow-hidden">

              {/* Tab Switcher */}
              <div className="flex border-b border-slate-100">
                {([
                  { key: 'login', label: 'Login User', icon: <User size={13} /> },
                  { key: 'register-user', label: 'Daftar User', icon: <UserCheck size={13} /> },
                ] as const).map(t => (
                  <button key={t.key} onClick={() => { setTab(t.key); clear(); }}
                    className={`flex-1 flex items-center justify-center gap-1.5 py-3.5 text-[11px] font-black uppercase tracking-wider transition-all border-b-2 ${
                      tab === t.key
                        ? 'border-emerald-500 text-emerald-700 bg-emerald-50/50'
                        : 'border-transparent text-slate-400 hover:text-slate-600 hover:bg-slate-50'
                    }`}>
                    {t.icon} <span className="hidden sm:inline">{t.label}</span>
                  </button>
                ))}
              </div>

              <div className="p-7">
                <AnimatePresence mode="wait">

                  {/* ── LOGIN USER ── */}
                  {tab === 'login' && (
                    <motion.form key="login" initial={{ opacity:0, y:8 }} animate={{ opacity:1, y:0 }} exit={{ opacity:0, y:-8 }}
                      onSubmit={handleLogin} className="space-y-4">
                      <div>
                        <h2 className="text-xl font-black text-slate-900 mb-0.5">Halo! Yuk Masuk</h2>
                        <p className="text-slate-400 text-xs">Cek aset-asetmu di sini, semuanya sudah rapi.</p>
                      </div>
                      <div className="space-y-3">
                        <div>
                          <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest pl-0.5 mb-1.5 block">Email</label>
                          <input type="email" value={loginEmail} onChange={e => setLoginEmail(e.target.value)} required
                            placeholder="email@contoh.com"
                            className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 text-sm text-slate-900 focus:outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/10 transition-all placeholder:text-slate-300" />
                        </div>
                        <div>
                          <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest pl-0.5 mb-1.5 block">Password</label>
                          <div className="relative">
                            <input type={showPw ? 'text' : 'password'} value={loginPw} onChange={e => setLoginPw(e.target.value)} required
                              placeholder="••••••••"
                              className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 pr-10 text-sm text-slate-900 focus:outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/10 transition-all" />
                            <button type="button" onClick={() => setShowPw(!showPw)} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600">
                              {showPw ? <EyeOff size={15} /> : <Eye size={15} />}
                            </button>
                          </div>
                        </div>
                      </div>
                      {error && <p className="text-red-500 text-xs bg-red-50 border border-red-100 px-3 py-2 rounded-lg">{error}</p>}
                      <button type="submit" className="w-full bg-emerald-600 hover:bg-emerald-700 text-white font-black py-3.5 rounded-xl transition-all flex items-center justify-center gap-2 group shadow-lg shadow-emerald-600/15">
                        Masuk ke Dashboard <ArrowRight size={16} className="group-hover:translate-x-0.5 transition-transform" />
                      </button>
                      <p className="text-center text-xs text-slate-400">Belum punya akun?{' '}
                        <button type="button" onClick={() => { setTab('register-user'); clear(); }} className="text-emerald-600 font-bold hover:underline">Daftar sekarang</button>
                      </p>
                    </motion.form>
                  )}

                  {/* ── REGISTER USER ── */}
                  {tab === 'register-user' && (
                    <motion.form key="reg-user" initial={{ opacity:0, y:8 }} animate={{ opacity:1, y:0 }} exit={{ opacity:0, y:-8 }}
                      onSubmit={handleRegisterUser} className="space-y-4">
                      <div>
                        <h2 className="text-xl font-black text-slate-900 mb-0.5">Daftar Akun Baru</h2>
                        <p className="text-slate-400 text-xs">Cukup isi data singkat buat mulai kelola aset digitalmu.</p>
                      </div>
                      <div className="space-y-3">
                        {[
                          { label: 'Nama Lengkap', type: 'text', value: regName, onChange: setRegName, placeholder: 'Budi Santoso' },
                          { label: 'Email', type: 'email', value: regEmail, onChange: setRegEmail, placeholder: 'email@contoh.com' },
                        ].map(f => (
                          <div key={f.label}>
                            <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest pl-0.5 mb-1.5 block">{f.label}</label>
                            <input type={f.type} value={f.value} onChange={e => f.onChange(e.target.value)} required placeholder={f.placeholder}
                              className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 text-sm text-slate-900 focus:outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/10 transition-all placeholder:text-slate-300" />
                          </div>
                        ))}
                        <div>
                          <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest pl-0.5 mb-1.5 block">Password</label>
                          <div className="relative">
                            <input type={showPw ? 'text' : 'password'} value={regPw} onChange={e => setRegPw(e.target.value)} required placeholder="Min. 6 karakter"
                              className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 pr-10 text-sm text-slate-900 focus:outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/10 transition-all" />
                            <button type="button" onClick={() => setShowPw(!showPw)} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400">
                              {showPw ? <EyeOff size={15} /> : <Eye size={15} />}
                            </button>
                          </div>
                        </div>
                      </div>
                      {error && <p className="text-red-500 text-xs bg-red-50 border border-red-100 px-3 py-2 rounded-lg">{error}</p>}
                      <button type="submit" className="w-full bg-emerald-600 hover:bg-emerald-700 text-white font-black py-3.5 rounded-xl transition-all flex items-center justify-center gap-2 group shadow-lg shadow-emerald-600/15">
                        Buat Akun & Masuk <ArrowRight size={16} className="group-hover:translate-x-0.5 transition-transform" />
                      </button>
                      <p className="text-center text-xs text-slate-400">Sudah punya akun?{' '}
                        <button type="button" onClick={() => { setTab('login'); clear(); }} className="text-emerald-600 font-bold hover:underline">Login</button>
                      </p>
                    </motion.form>
                  )}

                  {/* ── VALIDATOR CTA — pindahkan ke /daftarvalidator ── */}
                  {false && (
                    <motion.form key="reg-verif" initial={{ opacity:0, y:8 }} animate={{ opacity:1, y:0 }} exit={{ opacity:0, y:-8 }}
                      onSubmit={handleRegisterVerificator} className="space-y-4">
                      <div>
                        <h2 className="text-xl font-black text-slate-900 mb-0.5">Daftar Verificator</h2>
                        <p className="text-slate-400 text-xs">Permintaan akan di-review SuperAdmin sebelum akun aktif.</p>
                      </div>

                      {success ? (
                        <motion.div initial={{ opacity:0, scale:0.95 }} animate={{ opacity:1, scale:1 }}
                          className="bg-emerald-50 border border-emerald-200 rounded-2xl p-5 text-center">
                          <CheckCircle2 size={32} className="text-emerald-500 mx-auto mb-3" />
                          <p className="font-black text-emerald-800 mb-1">Pendaftaran Berhasil!</p>
                          <p className="text-emerald-600 text-xs leading-relaxed">{success}</p>
                          <div className="mt-3 bg-white border border-emerald-100 rounded-xl px-4 py-2.5 text-left">
                            <p className="text-[10px] text-slate-400 font-black uppercase tracking-widest mb-1">Selanjutnya</p>
                            <ol className="text-xs text-slate-600 space-y-1">
                              <li>1. Tunggu persetujuan SuperAdmin di <code className="bg-slate-100 px-1 rounded">/admin</code></li>
                              <li>2. Setelah disetujui, login ke <button type="button" onClick={() => router.push('/verificator')} className="text-emerald-600 font-bold underline">/verificator</button></li>
                              <li>3. Gunakan <strong>username</strong> dan <strong>password</strong> yang sudah dibuat</li>
                            </ol>
                          </div>
                        </motion.div>
                      ) : (
                        <>
                          <div className="space-y-3">
                            {/* Username */}
                            <div>
                              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest pl-0.5 mb-1.5 block">
                                Username <span className="text-red-400">*</span>
                              </label>
                              <input value={vUsername} onChange={e => setVUsername(e.target.value)} required
                                placeholder="notaris_budi (3-20 karakter, huruf/angka/underscore)"
                                className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 text-sm text-slate-900 font-mono focus:outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/10 transition-all placeholder:text-slate-300 placeholder:font-sans" />
                              <p className="text-[10px] text-slate-400 mt-1 pl-1">Digunakan untuk login ke portal Verificator</p>
                            </div>

                            {/* Nama Lengkap */}
                            <div>
                              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest pl-0.5 mb-1.5 block">
                                Nama Lengkap <span className="text-red-400">*</span>
                              </label>
                              <input value={vName} onChange={e => setVName(e.target.value)} required
                                placeholder="Nama Notaris / Pejabat"
                                className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 text-sm text-slate-900 focus:outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/10 transition-all placeholder:text-slate-300" />
                            </div>

                            {/* Wallet Address */}
                            <div>
                              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest pl-0.5 mb-1.5 block">
                                Alamat Wallet (0x...) <span className="text-red-400">*</span>
                              </label>
                              <div className="relative">
                                <div className="absolute left-4 top-1/2 -translate-y-1/2"><Wallet size={14} className="text-slate-400" /></div>
                                <input value={vWallet} onChange={e => setVWallet(e.target.value)} required
                                  placeholder="0x1234...abcd (42 karakter)"
                                  className="w-full bg-slate-50 border border-slate-200 rounded-xl pl-10 pr-4 py-3 text-sm font-mono text-slate-900 focus:outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/10 transition-all placeholder:text-slate-300 placeholder:font-sans" />
                              </div>
                              <p className="text-[10px] text-slate-400 mt-1 pl-1">Wallet address Anda di Base Sepolia — digunakan untuk menerima reward verifikasi (0.0008 ETH)</p>
                            </div>

                            {/* Institusi */}
                            <div>
                              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest pl-0.5 mb-1.5 block">
                                Institusi / Lembaga <span className="text-red-400">*</span>
                              </label>
                              <input value={vInstitution} onChange={e => setVInstitution(e.target.value)} required
                                placeholder="Kantor Notaris / BPN / Asuransi / PPAT"
                                className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 text-sm text-slate-900 focus:outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/10 transition-all placeholder:text-slate-300" />
                            </div>

                            {/* Password */}
                            <div>
                              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest pl-0.5 mb-1.5 block">
                                Password <span className="text-red-400">*</span> <span className="text-slate-300 font-normal">(min. 8 karakter)</span>
                              </label>
                              <div className="relative">
                                <input type={showPw ? 'text' : 'password'} value={vPw} onChange={e => setVPw(e.target.value)} required
                                  placeholder="Min. 8 karakter"
                                  className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 pr-10 text-sm text-slate-900 focus:outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/10 transition-all" />
                                <button type="button" onClick={() => setShowPw(!showPw)} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400">
                                  {showPw ? <EyeOff size={15} /> : <Eye size={15} />}
                                </button>
                              </div>
                            </div>

                            {/* Konfirmasi Password */}
                            <div>
                              <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest pl-0.5 mb-1.5 block">
                                Konfirmasi Password <span className="text-red-400">*</span>
                              </label>
                              <div className="relative">
                                <input type={showPw2 ? 'text' : 'password'} value={vPwConfirm} onChange={e => setVPwConfirm(e.target.value)} required
                                  placeholder="Ulangi password"
                                  className={`w-full bg-slate-50 border rounded-xl px-4 py-3 pr-10 text-sm text-slate-900 focus:outline-none focus:ring-2 transition-all ${
                                    vPwConfirm && vPw !== vPwConfirm
                                      ? 'border-red-300 focus:border-red-400 focus:ring-red-400/10'
                                      : vPwConfirm && vPw === vPwConfirm
                                      ? 'border-emerald-300 focus:border-emerald-400 focus:ring-emerald-400/10'
                                      : 'border-slate-200 focus:border-blue-500 focus:ring-blue-500/10'
                                  }`} />
                                <button type="button" onClick={() => setShowPw2(!showPw2)} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400">
                                  {showPw2 ? <EyeOff size={15} /> : <Eye size={15} />}
                                </button>
                              </div>
                              {vPwConfirm && vPw !== vPwConfirm && (
                                <p className="text-red-500 text-[10px] mt-1 pl-1">Password tidak cocok</p>
                              )}
                              {vPwConfirm && vPw === vPwConfirm && (
                                <p className="text-emerald-600 text-[10px] mt-1 pl-1 flex items-center gap-1"><CheckCircle2 size={10} /> Password cocok</p>
                              )}
                            </div>
                          </div>

                          {/* Security note */}
                          <div className="bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 flex items-start gap-2.5">
                            <Hash size={13} className="text-slate-400 shrink-0 mt-0.5" />
                            <p className="text-[11px] text-slate-500 leading-relaxed">
                              Password di-hash menggunakan <strong>SHA-256</strong> sebelum disimpan. Plain text password tidak pernah tersimpan di sistem.
                            </p>
                          </div>

                          {error && <p className="text-red-500 text-xs bg-red-50 border border-red-100 px-3 py-2 rounded-lg">{error}</p>}

                          <button type="submit" disabled={isHashing}
                            className="w-full bg-blue-600 hover:bg-blue-700 disabled:opacity-60 text-white font-black py-3.5 rounded-xl transition-all flex items-center justify-center gap-2 group shadow-lg shadow-blue-600/15">
                            {isHashing ? 'Mengenkripsi password...' : <><span>Daftar Verificator</span> <ArrowRight size={16} className="group-hover:translate-x-0.5 transition-transform" /></>}
                          </button>

                          <div className="bg-amber-50 border border-amber-100 rounded-xl px-4 py-3 flex items-start gap-2.5">
                            <div className="w-1.5 h-1.5 rounded-full bg-amber-400 mt-1.5 shrink-0" />
                            <p className="text-[11px] text-amber-700 leading-relaxed">
                              Setelah mendaftar, SuperAdmin harus menyetujui akun Anda. Login melalui{' '}
                              <button type="button" onClick={() => router.push('/verificator')} className="font-bold underline">/verificator</button>{' '}
                              menggunakan username dan password yang sudah dibuat.
                            </p>
                          </div>
                        </>
                      )}
                    </motion.form>
                  )}
                </AnimatePresence>
              </div>

              <div className="border-t border-slate-100 pt-3 mt-1 space-y-1.5">
              </div>
            </div>
          </motion.div>
        </div>

        {/* ── How It Works ── */}
        <section className="pb-20 border-t border-slate-100 pt-14">
          <div className="text-center mb-10">
            <h2 className="text-2xl font-black text-slate-900 tracking-tight mb-2">Gimana Sih Cara Kerjanya?</h2>
            <p className="text-slate-400 text-sm">Gak pake ribet, cuma 3 langkah buat ubah aset fisikmu jadi aset digital yang aman.</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
            {[
              { n:'01', icon:<Landmark size={22} className="text-emerald-600"/>, title:'Daftar Asetmu', desc:'Gak ribet, tinggal upload foto atau PDF dokumen asetmu (kayak sertifikat tanah atau BPKB). Kita bakal simpan "sidik jari" digitalnya di blockchain biar data asetmu aman dan gak bisa dimanipulasi.' },
              { n:'02', icon:<ShieldCheck size={22} className="text-emerald-600"/>, title:'Dicek Sama Ahlinya', desc:'Verifikator resmi (kayak notaris atau instansi terkait) bakal ngecek keaslian dokumenmu. Mereka bakal mastiin asetmu valid dan siap jadi aset digital yang sah buat kamu kelola.' },
              { n:'03', icon:<Coins size={22} className="text-emerald-600"/>, title:'Pantau & Kelola', desc:'Sekarang aset fisikmu udah punya "kembaran" digital. Kamu bisa cek nilainya kapan aja, pindahin kepemilikannya, atau simpan buat investasi. Semuanya tercatat rapi dan aman.' },
            ].map(s => (
              <div key={s.n} className="bg-white border border-slate-100 rounded-2xl p-6 hover:shadow-md hover:-translate-y-0.5 transition-all">
                <div className="flex items-start justify-between mb-5">
                  <div className="w-11 h-11 bg-emerald-50 rounded-xl flex items-center justify-center border border-emerald-100">{s.icon}</div>
                  <span className="text-3xl font-black text-slate-100">{s.n}</span>
                </div>
                <h3 className="font-black text-slate-900 mb-2">{s.title}</h3>
                <p className="text-slate-400 text-xs leading-relaxed">{s.desc}</p>
              </div>
            ))}
          </div>
        </section>
      </div>
    </div>
  );
}

