'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import { motion } from 'framer-motion';

export default function RegisterPage() {
  const router = useRouter();
  
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  
  // Tabs: 'masyarakat' or 'pejabat'
  const [registerType, setRegisterType] = useState<'masyarakat' | 'pejabat'>('masyarakat');

  // Form State
  const [name, setName] = useState('');
  const [wallet, setWallet] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  
  // Specific to Masyarakat
  const [email, setEmail] = useState('');
  
  // Specific to Pejabat
  const [institution, setInstitution] = useState('NOTARIS');
  const [evidenceFile, setEvidenceFile] = useState<File | null>(null);

  const getEvidenceHint = () => {
    switch (institution) {
      case 'NOTARIS':
        return 'Syarat Dokumen: SK Pengangkatan Kemenkumham & KTA INI/IPPAT aktif.';
      case 'AUDITOR':
        return 'Syarat Dokumen: Surat Perintah Tugas / Penyelidikan & ID Card Instansi.';
      case 'BPN_WILAYAH':
        return 'Syarat Dokumen: SK Penempatan & ID Card Pegawai BPN.';
      case 'BPN_PUSAT':
        return 'Syarat Dokumen: Surat Tugas Khusus Admin Pusat.';
      default:
        return 'Upload dokumen pendukung yang valid.';
    }
  };

  const handleRegister = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setSuccess('');
    setLoading(true);

    try {
      if (password !== confirmPassword) {
        throw new Error('Password dan Konfirmasi Password tidak cocok!');
      }

      const { supabase } = await import('@/lib/supabase');

      if (registerType === 'masyarakat') {
        if (!name || !email || !wallet || !password) throw new Error('Harap lengkapi semua data.');
        
        // 1. Sign Up using Supabase Auth
        const { data: authData, error: authErr } = await supabase.auth.signUp({
          email: email,
          password: password,
        });

        if (authErr) throw new Error(authErr.message);
        if (!authData.user) throw new Error('Gagal membuat akun.');

        // 2. Update the profile (Trigger created the row with UMUM)
        const { error: dbErr } = await supabase.from('profiles').update({
          full_name: name,
          wallet_address: wallet.toLowerCase(),
          role: 'UMUM'
        }).eq('id', authData.user.id);

        if (dbErr) {
          console.error("Gagal update profil:", dbErr.message);
        }

        setSuccess('Registrasi berhasil! Anda dapat langsung login sekarang.');
        setTimeout(() => router.push('/login'), 2000);

      } else {
        if (!email || !name || !wallet || !password || !evidenceFile) {
          throw new Error('Harap lengkapi semua data, termasuk File Bukti Dokumen.');
        }

        // 1. Upload File ke Pinata (IPFS)
        setSuccess('Mengunggah dokumen ke IPFS (Pinata)...');
        const { uploadToIPFS } = await import('@/lib/pinata');
        const ipfsHash = await uploadToIPFS(evidenceFile);
        const finalEvidenceUrl = `ipfs://${ipfsHash}`;

        setSuccess('Mendaftarkan akun ke sistem...');
        // 2. Sign Up using Supabase Auth
        const { data: authData, error: authErr } = await supabase.auth.signUp({
          email: email,
          password: password,
        });

        if (authErr) throw new Error(authErr.message);
        if (!authData.user) throw new Error('Gagal membuat akun.');

        // 3. Update the profile generated by the trigger
        setSuccess('Menyimpan profil dan dokumen validasi...');
        const { error: dbErr } = await supabase.from('profiles').update({
          full_name: name,
          wallet_address: wallet.toLowerCase(),
          role: institution,
          evidence_url: finalEvidenceUrl,
          verification_status: 'PENDING'
        }).eq('id', authData.user.id);

        if (dbErr) throw new Error(dbErr.message);

        setSuccess('Pendaftaran Pejabat berhasil! Menunggu persetujuan (Approval) dari Admin BPN Pusat.');
        setTimeout(() => router.push('/login'), 3500);
      }
    } catch (err: any) {
      setError(err.message || 'Terjadi kesalahan saat registrasi.');
      setSuccess('');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen w-full flex bg-[#fbfcf8] font-sans">
      {/* Left Pane (Info) */}
      <div className="hidden lg:flex w-1/2 bg-moss-900 relative overflow-hidden flex-col justify-between p-16">
        <div className="absolute inset-0 bg-moss-800 mix-blend-overlay opacity-30"></div>
        <div className="absolute top-0 right-0 w-[800px] h-[800px] bg-olive-500 rounded-full blur-[150px] opacity-20 -translate-y-1/2 translate-x-1/3"></div>
        <div className="absolute bottom-0 left-0 w-[600px] h-[600px] bg-moss-400 rounded-full blur-[120px] opacity-20 translate-y-1/3 -translate-x-1/3"></div>
        
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          className="relative z-10 flex items-center gap-4"
        >
          <div className="bg-white/10 backdrop-blur-md p-3 rounded-2xl border border-white/20">
            <img src="/logo.png" alt="Bhumi Logo" className="h-10 w-10 object-contain brightness-0 invert" />
          </div>
          <h1 className="text-3xl font-extrabold text-white tracking-tight">Bhumi</h1>
        </motion.div>

        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.2 }}
          className="relative z-10 max-w-lg"
        >
          <h2 className="text-5xl font-bold text-white leading-tight mb-6">
            Pendaftaran<br/>
            <span className="text-olive-300">Akses Sistem.</span>
          </h2>
          <p className="text-moss-100/90 text-lg leading-relaxed">
            Bergabunglah dengan ekosistem pertanahan masa depan. Proses verifikasi berlapis memastikan keamanan dan integritas setiap transaksi hak milik Anda.
          </p>
        </motion.div>
      </div>

      {/* Right Pane (Form) */}
      <div className="w-full lg:w-1/2 flex items-center justify-center p-8 relative overflow-y-auto">
        <motion.div 
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.5 }}
          className="w-full max-w-lg bg-white p-10 rounded-[2rem] shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-moss-100/50 my-auto"
        >
          <div className="mb-8 text-center">
            <h3 className="text-2xl font-bold text-gray-900 mb-2">Buat Akun Baru</h3>
            <p className="text-moss-600/70 text-sm">Pilih jenis akun yang sesuai dengan peran Anda</p>
          </div>

          {/* Toggle Register Type */}
          <div className="flex p-1 bg-moss-50 rounded-xl mb-8">
            <button
              type="button"
              onClick={() => { setRegisterType('masyarakat'); setError(''); setSuccess(''); }}
              className={`flex-1 py-2 text-sm font-bold rounded-lg transition-all ${registerType === 'masyarakat' ? 'bg-white text-moss-800 shadow-sm border border-moss-200/50' : 'text-moss-500 hover:text-moss-700'}`}
            >
              Masyarakat Umum
            </button>
            <button
              type="button"
              onClick={() => { setRegisterType('pejabat'); setError(''); setSuccess(''); }}
              className={`flex-1 py-2 text-sm font-bold rounded-lg transition-all ${registerType === 'pejabat' ? 'bg-white text-moss-800 shadow-sm border border-moss-200/50' : 'text-moss-500 hover:text-moss-700'}`}
            >
              Pejabat / Instansi
            </button>
          </div>

          <form onSubmit={handleRegister} className="space-y-5">
            {registerType === 'masyarakat' ? (
              /* ================= FORM MASYARAKAT ================= */
              <>
                <div>
                  <label className="block text-xs font-bold text-moss-800 uppercase tracking-widest mb-2">Nama Lengkap</label>
                  <input type="text" value={name} onChange={(e) => setName(e.target.value)} placeholder="Sesuai KTP" className="w-full px-4 py-3 border border-moss-200 rounded-xl focus:ring-2 focus:ring-olive-500 outline-none" />
                </div>
                <div>
                  <label className="block text-xs font-bold text-moss-800 uppercase tracking-widest mb-2">Email</label>
                  <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="nama@email.com" className="w-full px-4 py-3 border border-moss-200 rounded-xl focus:ring-2 focus:ring-olive-500 outline-none" />
                </div>
                <div>
                  <label className="block text-xs font-bold text-moss-800 uppercase tracking-widest mb-2">Wallet Address (MetaMask)</label>
                  <input type="text" value={wallet} onChange={(e) => setWallet(e.target.value)} placeholder="0x..." className="w-full px-4 py-3 border border-moss-200 rounded-xl focus:ring-2 focus:ring-olive-500 outline-none font-mono text-sm" />
                </div>
                <div className="flex gap-4">
                  <div className="flex-1">
                    <label className="block text-xs font-bold text-moss-800 uppercase tracking-widest mb-2">Password</label>
                    <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="••••••••" className="w-full px-4 py-3 border border-moss-200 rounded-xl focus:ring-2 focus:ring-olive-500 outline-none" />
                  </div>
                  <div className="flex-1">
                    <label className="block text-xs font-bold text-moss-800 uppercase tracking-widest mb-2">Konfirmasi Password</label>
                    <input type="password" value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} placeholder="••••••••" className="w-full px-4 py-3 border border-moss-200 rounded-xl focus:ring-2 focus:ring-olive-500 outline-none" />
                  </div>
                </div>
              </>
            ) : (
              /* ================= FORM PEJABAT ================= */
              <>
                <div className="flex gap-4">
                  <div className="flex-1">
                    <label className="block text-xs font-bold text-moss-800 uppercase tracking-widest mb-2">Email Instansi</label>
                    <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="nama@instansi.go.id" className="w-full px-4 py-3 border border-moss-200 rounded-xl focus:ring-2 focus:ring-olive-500 outline-none" />
                  </div>
                  <div className="flex-1">
                    <label className="block text-xs font-bold text-moss-800 uppercase tracking-widest mb-2">Nama Lengkap</label>
                    <input type="text" value={name} onChange={(e) => setName(e.target.value)} placeholder="Beserta Gelar" className="w-full px-4 py-3 border border-moss-200 rounded-xl focus:ring-2 focus:ring-olive-500 outline-none" />
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-bold text-moss-800 uppercase tracking-widest mb-2">Wallet Address (MetaMask)</label>
                  <input type="text" value={wallet} onChange={(e) => setWallet(e.target.value)} placeholder="0x..." className="w-full px-4 py-3 border border-moss-200 rounded-xl focus:ring-2 focus:ring-olive-500 outline-none font-mono text-sm" />
                </div>

                <div>
                  <label className="block text-xs font-bold text-moss-800 uppercase tracking-widest mb-2">Institusi / Jabatan</label>
                  <select value={institution} onChange={(e) => setInstitution(e.target.value)} className="w-full px-4 py-3 border border-moss-200 rounded-xl focus:ring-2 focus:ring-olive-500 outline-none bg-white font-medium text-gray-700">
                    <option value="NOTARIS">Notaris / PPAT</option>
                    <option value="AUDITOR">Auditor (KPK/BPK)</option>
                    <option value="BPN_WILAYAH">Petugas BPN Wilayah</option>
                  </select>
                </div>

                {/* Evidence Section - IPFS UPLOAD */}
                <div className="p-4 bg-orange-50 border border-orange-200 rounded-xl">
                  <label className="block text-xs font-bold text-orange-800 uppercase tracking-widest mb-1">Upload Bukti Validasi Jabatan</label>
                  <p className="text-xs text-orange-700 mb-3 font-medium">{getEvidenceHint()}</p>
                  
                  <input 
                    type="file" 
                    accept=".pdf,image/*"
                    onChange={(e) => setEvidenceFile(e.target.files?.[0] || null)} 
                    className="w-full px-4 py-2 border border-orange-300 rounded-lg focus:ring-2 focus:ring-orange-500 outline-none text-sm bg-white file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-xs file:font-semibold file:bg-orange-100 file:text-orange-700 hover:file:bg-orange-200" 
                  />
                  <p className="text-[10px] text-orange-600 mt-2">*Dokumen akan diamankan di IPFS (Pinata) dan diperiksa oleh BPN Pusat.</p>
                </div>

                <div className="flex gap-4">
                  <div className="flex-1">
                    <label className="block text-xs font-bold text-moss-800 uppercase tracking-widest mb-2">Password</label>
                    <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="••••••••" className="w-full px-4 py-3 border border-moss-200 rounded-xl focus:ring-2 focus:ring-olive-500 outline-none" />
                  </div>
                  <div className="flex-1">
                    <label className="block text-xs font-bold text-moss-800 uppercase tracking-widest mb-2">Konfirmasi Password</label>
                    <input type="password" value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} placeholder="••••••••" className="w-full px-4 py-3 border border-moss-200 rounded-xl focus:ring-2 focus:ring-olive-500 outline-none" />
                  </div>
                </div>
              </>
            )}

            {error && (
              <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} className="p-3 bg-red-50 text-red-600 rounded-lg text-sm font-medium border border-red-100 text-center">
                {error}
              </motion.div>
            )}

            {success && (
              <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} className="p-3 bg-green-50 text-green-700 rounded-lg text-sm font-medium border border-green-200 text-center">
                {success}
              </motion.div>
            )}

            <button
              type="submit"
              disabled={loading}
              className="w-full py-4 bg-moss-600 text-white font-bold rounded-xl hover:bg-moss-700 disabled:opacity-70 transition-all shadow-lg shadow-moss-600/20 mt-6"
            >
              {loading ? 'Memproses...' : 'Daftar Sekarang'}
            </button>
            
            <p className="text-center text-sm text-gray-500 mt-4">
              Sudah punya akun? <a href="/login" className="font-bold text-moss-600 hover:underline">Masuk di sini</a>
            </p>
          </form>
        </motion.div>
      </div>
    </div>
  );
}
